import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins, Roboto, TikTok_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/navbar/Navbar";
import Footer from "@/components/layouts/footer/Footer";
import BackToTop from "@/components/common/BackToTop";
import AlwaysTop from "@/components/common/AlwaysTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // istediğin ağırlıkları ekleyebilirsin
  variable: "--font-roboto", // optional: css variable olarak kullanmak için
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${geistMono.variable}`}>
        <Navbar />
        {children}
        <Footer />
        <BackToTop /> 
        <AlwaysTop /> 
      </body>
    </html>
  );
}
