import type { Metadata } from "next";
import { Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/navbar/Navbar";
import Footer from "@/components/layouts/footer/Footer";
import BackToTop from "@/components/common/BackToTop";
import AlwaysTop from "@/components/common/AlwaysTop";
import { HydrateGenres } from "@/components/api/HydrateGenres";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
    const apiKey = process.env.NEXT_PUBLIC_TMDB_API_KEY;

    const res = await fetch(
        `https://api.themoviedb.org/3/genre/movie/list?api_key=${apiKey}&language=en-US`,
        { cache: "force-cache" }
    );

    const data: { genres: { id: number; name: string }[] } = await res.json();

    return (
        <html lang="en">
        <body className={`${roboto.variable} ${geistMono.variable}`}>
            <Navbar />
            <HydrateGenres genres={data.genres}/>
            {children}
            <Footer />
            <BackToTop /> 
            <AlwaysTop />
        </body>
        </html>
    );
}
